### ISSUE TITLE
Creating a [better] remaps script

### ISSUE THREAD

**Issue by TrevCan** [LukeSmithxyz/voidrice#990]
When I first installed larbs on my computer, I was intrigued by the fact that the key combo CapsLock didn't work as states in the LARBS guide. I have now seen that there is an open issue regarding keys. 

I have since discovered the beauty of [interception](https://gitlab.com/interception/linux/tools/-/tree/master), basically a set of utilities for hijacking your input devices. Ok, maybe not that harsh, but, basically, it reads from input devices and translates them into new devices which have the correct layouts. 
For instance, it can work exactly as in the LARBS guide (provided you use the dual-function-keys plugin, both packages are available in the arch repos). You may specify this in a simple-to-use yaml file, which uses the [linux input event codes](https://github.com/torvalds/linux/blob/master/include/uapi/linux/input-event-codes.h)
Now,  for each physical key you'd like to modify, you'll have to specify the `TAP` and `HOLD` section, which can be the same if you only want it to act as another key. These entries may be a sequence of keys to be pressed or a single key. For instance, a simple key combo to work just as LARBS would be something like:
```
MAPPINGS:
  - KEY: KEY_CAPSLOCK
    TAP: KEY_ESC
    HOLD: KEY_LEFTCTRL
```
Yes!, as simple as that! The only other thing missing would be a `devmon.yaml` file which specifies the keyboard devices to intercept (ofc, pun intended). A catch-all keyboards config can be also made:
```
# lives under /etc/interception/udevmon.yaml
#
# Keyboard configuration. Important parts are `NAME:` and `EV_KEY`. Get the name of the devices you want this to apply to by using the command `evtest`, you should see the name of your keyboard somewhere, type the number and follow the instructions.

- JOB: "intercept -g $DEVNODE | dual-function-keys -c /etc/interception/dual-function-keys/keyboard.yaml | uinput -d $DEVNODE"
  DEVICE:
    NAME: .*[Kk]eyboard.*
    EVENTS:
      EV_KEY: [KEY_CAPSLOCK]
```
where `EV_KEY` is the list of physical keys that you'll modify and `/etc/interception/dual-function-keys/keyboard.yaml` is the actual keyboard mappings file.

Just my two cents, you may check out my config [here](https://gist.github.com/TrevCan/ea7a0c677b4345c464e1e4c04b3ca43f). Also, I've made a more detailed explanation on how to set this up in this [issue](https://gitlab.com/interception/linux/plugins/caps2esc/-/issues/21#note_661245975)

I don't think this would be too difficult to implement into larbs, just necessary to run it in the background on startup, e.g. in `.xprofile` and it'd work like a charm. **And yes, if I connect a bluetooth keyboard afterwards, re-running the script won't be needed**

Referenced packages;
- [interception-tools](https://archlinux.org/packages/community/x86_64/interception-tools/)
- [interception-dual-function-keys](https://archlinux.org/packages/community/x86_64/interception-dual-function-keys/)
